force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz</label>
    <nameField>
        <label>Quiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quizzes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quiz Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Question__c/fields/Allow_Multiple__c.field-meta.xml
<CustomField>
    <fullName>Allow_Multiple__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if question has multiple answers</description>
    <inlineHelpText>Checked if question has multiple answers</inlineHelpText>
    <label>Allow Multiple</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quiz_Question__c/fields/Correct_Answers__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answers__c</fullName>
    <label>Correct Answer(s)</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz_Question__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>5000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quiz_Question__c/fields/Quiz__c.field-meta.xml
<CustomField>
    <fullName>Quiz__c</fullName>
    <label>Quiz</label>
    <referenceTo>Quiz__c</referenceTo>
    <relationshipLabel>Quiz Questions</relationshipLabel>
    <relationshipName>Quiz_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuizController.cls
public with sharing class QuizController {
    @AuraEnabled(cacheable=true)
    public static List<Quiz_Question__c> getQuestions(Id quizId) {
        return [
            SELECT Id, Question_Text__c, Option_A__c, Option_B__c, Option_C__c, Option_D__c, Correct_Answers__c, Allow_Multiple__c
            FROM Quiz_Question__c
            WHERE Quiz__c = :quizId
            ORDER BY CreatedDate ASC
        ];
    }
}